version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://urlshortener:mysecretpassword@postgres:5432/urlshortener?sslmode=disable
      - PORT=8080
    ports:
      - "8080:8080"

volumes:
  postgres_data:
